-- Add protocols to platform_content
ALTER TABLE platform_content ADD COLUMN IF NOT EXISTS protocols JSONB DEFAULT '[]'::jsonb;

-- Insert initial values for protocols if the table is already populated
UPDATE platform_content 
SET protocols = '[
  {
    "title": "01. economics",
    "items": [
      "a one-time registration fee of rs. 800 covers identity onboarding and physical slot setup.",
      "shelf rent is fixed based on your selected tier (low, eye, or top) and commitment period (quarterly, half-yearly, or yearly).",
      "performance-based processing fees range from 3% to 10% based on monthly sales volume.",
      "high-performance brands (rs. 50k+ sales) qualify for 50% to 100% rent waivers for that month."
    ]
  },
  {
    "title": "02. payouts & data",
    "items": [
      "payouts are currently processed monthly, with goals to implement bill-based cycles as the collective scales.",
      "sales data and footfall insights will be provided via the brand dashboard as we refine our tracking systems.",
      "brands taking multiple shelves are eligible for custom fruitfull collaboration discounts."
    ]
  },
  {
    "title": "03. physical space",
    "items": [
      "location: bijeshwori, swyambhu. the club spans 3 rooms with 108 curated shelf spaces.",
      "shelf maintenance: brands must refresh stock at least once every 21 days to ensure the collective vibe remains fresh.",
      "cross-selling: brands acknowledge and benefit from footfall generated by sayummys cafe visitors.",
      "merchandising: we work together on placement and shelf design to optimize for customer behavior."
    ]
  },
  {
    "title": "04. liability & legal",
    "items": [
      "shopwear: given the high-traffic cafe environment, the club is not liable for minor damages from customer handling.",
      "curation: we gatekeep energy, not money. the club reserves the right to curate and select brands that fit the \"cool stuff\" mission.",
      "jurisdiction: this partnership and all digital/physical interactions are governed by the laws of kathmandu, nepal."
    ]
  }
]'::jsonb
WHERE id = 1 AND (protocols IS NULL OR protocols = '[]'::jsonb);
