-- Update platform_content schema and data
ALTER TABLE platform_content ADD COLUMN IF NOT EXISTS origins TEXT;

UPDATE platform_content 
SET 
  origins = '# our origins

this didn’t start as an idea. it started as frustration.

before thc club, we were on the other side of the counter—trying to sell our own products.
what we found was simple: visibility wasn’t earned, it was taxed.

most stores asked for 20% to 35% commission.
at that point, they weren’t just a platform—they were silent partners without the risk, without the paperwork.

we tried a different approach.
we asked for something smaller. a fixed space. lower commission. room to experiment.

no one agreed.

so we stopped asking.

kathmandu is full of creators building genuinely great products—out of bedrooms, small kitchens, late nights.
but getting discovered? that’s a different game entirely. expensive shelves, algorithm dependency, or both.

that gap—between creating and being seen—is where most brands die.

the hidden collective club was built to close that gap.

not by taking a bigger cut, but by changing the model entirely.

we offer space, visibility, shared footfall, and real-world presence—without turning creators into margin for someone else.

you bring the product.
we make sure it gets seen.

simple.',
  protocols = '[
    {
      "title": "01. economics",
      "items": [
        "a one-time registration fee of rs. 800 covers identity onboarding and physical slot setup.",
        "shelf rent is fixed based on your selected tier (low, eye, or top) and commitment period (quarterly, half-yearly, or yearly).",
        "performance-based processing fees range from 3% to 10% based on monthly sales volume.",
        "high-performance brands (rs. 50k+ sales) qualify for 50% to 100% rent waivers for that month."
      ]
    },
    {
      "title": "02. payouts & data",
      "items": [
        "payouts are currently processed monthly, with goals to implement bill-based cycles as the collective scales.",
        "sales data and footfall insights will be provided via the brand dashboard as we refine our tracking systems.",
        "brands taking multiple shelves are eligible for custom fruitfull collaboration discounts."
      ]
    },
    {
      "title": "03. physical space",
      "items": [
        "location: bijeshwori, swyambhu. the club spans 3 rooms with 108 curated shelf spaces.",
        "shelf maintenance: brands must refresh stock at least once every 21 days to ensure the collective vibe remains fresh.",
        "cross-selling: brands acknowledge and benefit from footfall generated by sayummys cafe visitors.",
        "merchandising: we work together on placement and shelf design to optimize for customer behavior."
      ]
    },
    {
      "title": "04. liability & legal",
      "items": [
        "shopwear: given the high-traffic cafe environment, the club is not liable for minor damages from customer handling.",
        "curation: we gatekeep energy, not money. the club reserves the right to curate and select brands that fit the \"cool stuff\" mission.",
        "jurisdiction: this partnership and all digital/physical interactions are governed by the laws of kathmandu, nepal."
      ]
    }
  ]'::jsonb,
  terms_conditions = 'THE HIDDEN COLLECTIVE CLUB (THC CLUB)
PARTNERSHIP TERMS & CONDITIONS
v1.0 • Effective 2026

1. REGISTRATION & ONBOARDING
1.1 A one-time registration fee of NPR 800 is required upon acceptance into the collective.
1.2 This fee covers digital identity verification, administrative onboarding, and the physical preparation of the allotted shelf space. 
1.3 Acceptance is at the sole discretion of the THC Club curation team, focusing on brand alignment and product quality.

2. SHELF RENTAL & PLACEMENT
2.1 Monthly rent is determined by the selected tier (Top, Eye, or Low level) and the commitment cycle (Quarterly, Half-Yearly, or Yearly).
2.2 Specific shelf slot assignments within a selected tier are determined by THC Club to ensure optimal collective merchandising.
2.3 Rent is payable in advance according to the agreed payment schedule (Bank Transfer, QR, or Cash).

3. PERFORMANCE-BASED PROCESSING FEES (PPF)
3.1 In addition to rent, a performance-based processing fee (PPF) ranging from 3% to 10% of gross sales is applied.
3.2 High-performance incentive: Brands achieving gross monthly sales of NPR 50,000 or more are eligible for the Rent Waiver program, where a portion or all of the following month s rent may be waived.

4. PAYOUTS & FINANCIAL RECONCILIATION
4.1 Sales are tracked through the THC Club POS system.
4.2 Payouts of net sales (Gross Sales minus PPF and any outstanding fees) are currently processed on a monthly cycle.
4.3 Brands can monitor real-time sales estimates via the THC Club Brand Portal.

5. PHYSICAL SPACE & MAINTENANCE
5.1 Brands are responsible for maintaining their stock levels. A minimum stock refresh is required at least once every 21 days.
5.2 THC Club provides the shared footfall and physical visibility, including exposure from neighboring Sayummys Cafe.
5.3 Brands must adhere to the merchandising standards of the collective.

6. LIABILITY & LIMITATIONS
6.1 In the event of minor damage or wear caused by customer handling (shopwear), THC Club shall not be held liable, given the high-traffic nature of the environment.
6.2 THC Club reserves the right to re-curate or terminate partnerships if brand standards are not maintained, with a 30-day notice period.

7. LEGAL JURISDICTION
7.1 This partnership is governed by the laws of Kathmandu, Nepal.
7.2 Digital acceptance of these terms constitutes a binding agreement between the Brand Partner and The Hidden Collective Club.',
  updated_at = now()
WHERE id = 1;
