-- ============================================================
-- THC Club Platform - Full Production Migration
-- Run this entire script in the Supabase SQL Editor
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- Table: brands
-- Extended profile for each approved brand/user
-- ============================================================
CREATE TABLE IF NOT EXISTS brands (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES approved_users(id) ON DELETE CASCADE,
  business_name TEXT NOT NULL,
  contact_name TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  description TEXT,
  logo_url TEXT,
  instagram_handle TEXT,
  onboarding_status TEXT NOT NULL DEFAULT 'pending' 
    CHECK (onboarding_status IN ('pending', 'slot_selected', 'confirmed', 'active', 'rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Table: shelf_bookings
-- Booking lifecycle: pending -> approved -> active
-- ============================================================
CREATE TABLE IF NOT EXISTS shelf_bookings (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  shelf_type TEXT NOT NULL CHECK (shelf_type IN ('bottom', 'eye_level', 'top_level')),
  duration TEXT NOT NULL CHECK (duration IN ('quarterly', 'half_yearly', 'yearly')),
  slot_number INTEGER,
  monthly_rent NUMERIC(10,2) NOT NULL,
  total_amount NUMERIC(10,2) NOT NULL,
  start_date DATE,
  end_date DATE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'active', 'expired')),
  admin_notes TEXT,
  brand_agreement_accepted BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Table: brand_products
-- Product catalog for each brand
-- ============================================================
CREATE TABLE IF NOT EXISTS brand_products (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  sku TEXT,
  description TEXT,
  category TEXT,
  price NUMERIC(10,2) NOT NULL DEFAULT 0,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  low_stock_threshold INTEGER NOT NULL DEFAULT 5,
  image_url TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Table: invoices
-- Invoice header (generated by admin/store user)
-- ============================================================
CREATE TABLE IF NOT EXISTS invoices (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_number TEXT NOT NULL UNIQUE,
  brand_id UUID REFERENCES brands(id) ON DELETE RESTRICT,
  created_by TEXT NOT NULL,  -- admin username
  customer_name TEXT,
  customer_phone TEXT,
  subtotal NUMERIC(10,2) NOT NULL DEFAULT 0,
  discount_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
  commission_rate NUMERIC(5,2),
  commission_amount NUMERIC(10,2),
  payment_method TEXT DEFAULT 'cash'
    CHECK (payment_method IN ('cash', 'card', 'qr', 'transfer')),
  status TEXT NOT NULL DEFAULT 'paid'
    CHECK (status IN ('draft', 'paid', 'refunded')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Table: invoice_line_items
-- Individual products on each invoice
-- ============================================================
CREATE TABLE IF NOT EXISTS invoice_line_items (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  invoice_id UUID REFERENCES invoices(id) ON DELETE CASCADE,
  product_id UUID REFERENCES brand_products(id) ON DELETE RESTRICT,
  product_name TEXT NOT NULL,
  product_sku TEXT,
  unit_price NUMERIC(10,2) NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  line_total NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- Table: brand_sales
-- Monthly aggregated sales tracker per brand
-- (auto-updated by trigger on invoice insert)
-- ============================================================
CREATE TABLE IF NOT EXISTS brand_sales (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  brand_id UUID REFERENCES brands(id) ON DELETE CASCADE,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL,
  gross_sales NUMERIC(10,2) NOT NULL DEFAULT 0,
  invoice_count INTEGER NOT NULL DEFAULT 0,
  commission_rate NUMERIC(5,2),
  commission_amount NUMERIC(10,2) DEFAULT 0,
  rent_waiver_percent INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (brand_id, month, year)
);

-- ============================================================
-- Function: Generate Invoice Number
-- ============================================================
CREATE OR REPLACE FUNCTION generate_invoice_number()
RETURNS TEXT AS $$
DECLARE
  seq INTEGER;
  invoice_no TEXT;
BEGIN
  SELECT COALESCE(MAX(CAST(SPLIT_PART(invoice_number, '-', 2) AS INTEGER)), 0) + 1
  INTO seq
  FROM invoices
  WHERE invoice_number LIKE 'INV-%';
  
  invoice_no := 'INV-' || LPAD(seq::TEXT, 5, '0');
  RETURN invoice_no;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
-- Function: Update brand_sales on invoice insert
-- ============================================================
CREATE OR REPLACE FUNCTION update_brand_sales_on_invoice()
RETURNS TRIGGER AS $$
DECLARE
  sale_month INTEGER;
  sale_year INTEGER;
  new_gross NUMERIC(10,2);
  new_count INTEGER;
  commission NUMERIC(5,2);
  waiver INTEGER;
BEGIN
  sale_month := EXTRACT(MONTH FROM NEW.created_at);
  sale_year := EXTRACT(YEAR FROM NEW.created_at);

  -- Upsert into brand_sales
  INSERT INTO brand_sales (brand_id, month, year, gross_sales, invoice_count)
  VALUES (NEW.brand_id, sale_month, sale_year, NEW.total_amount, 1)
  ON CONFLICT (brand_id, month, year)
  DO UPDATE SET
    gross_sales = brand_sales.gross_sales + NEW.total_amount,
    invoice_count = brand_sales.invoice_count + 1,
    updated_at = NOW();

  -- Recalculate commission and waiver
  SELECT gross_sales INTO new_gross
  FROM brand_sales
  WHERE brand_id = NEW.brand_id AND month = sale_month AND year = sale_year;

  IF new_gross >= 100000 THEN
    commission := 10; waiver := 100;
  ELSIF new_gross >= 50000 THEN
    commission := 7; waiver := 50;
  ELSIF new_gross >= 10000 THEN
    commission := 5; waiver := 0;
  ELSE
    commission := 3; waiver := 0;
  END IF;

  UPDATE brand_sales
  SET
    commission_rate = commission,
    commission_amount = ROUND(new_gross * commission / 100, 2),
    rent_waiver_percent = waiver
  WHERE brand_id = NEW.brand_id AND month = sale_month AND year = sale_year;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach trigger to invoices table
DROP TRIGGER IF EXISTS trg_update_brand_sales ON invoices;
CREATE TRIGGER trg_update_brand_sales
AFTER INSERT ON invoices
FOR EACH ROW EXECUTE FUNCTION update_brand_sales_on_invoice();

-- ============================================================
-- Function: Decrement stock on invoice line item insert
-- ============================================================
CREATE OR REPLACE FUNCTION decrement_stock_on_invoice_item()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE brand_products
  SET
    stock_quantity = GREATEST(stock_quantity - NEW.quantity, 0),
    updated_at = NOW()
  WHERE id = NEW.product_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_decrement_stock ON invoice_line_items;
CREATE TRIGGER trg_decrement_stock
AFTER INSERT ON invoice_line_items
FOR EACH ROW EXECUTE FUNCTION decrement_stock_on_invoice_item();

-- ============================================================
-- Function: Auto update updated_at on row change
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Attach updated_at trigger to all relevant tables
DO $$
DECLARE
  t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['brands','shelf_bookings','brand_products','invoices','brand_sales']
  LOOP
    EXECUTE FORMAT(
      'DROP TRIGGER IF EXISTS trg_updated_at ON %I; 
       CREATE TRIGGER trg_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at();',
      t, t
    );
  END LOOP;
END;
$$;

-- ============================================================
-- Row Level Security (disable for service role, enable for anon)
-- Note: Supabase anon key respects RLS. For now using service role
-- on backend calls, so we ensure tables are accessible.
-- ============================================================
ALTER TABLE brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE shelf_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE invoice_line_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE brand_sales ENABLE ROW LEVEL SECURITY;

-- Allow all for authenticated (service role bypasses RLS automatically)
CREATE POLICY "allow_all" ON brands FOR ALL USING (true);
CREATE POLICY "allow_all" ON shelf_bookings FOR ALL USING (true);
CREATE POLICY "allow_all" ON brand_products FOR ALL USING (true);
CREATE POLICY "allow_all" ON invoices FOR ALL USING (true);
CREATE POLICY "allow_all" ON invoice_line_items FOR ALL USING (true);
CREATE POLICY "allow_all" ON brand_sales FOR ALL USING (true);

-- ============================================================
-- DONE
-- ============================================================
